### ISSUE TITLE
Update Icons

### ISSUE THREAD

**Issue by Stazed** [Stazed/rakarrack-plus#1]
..doc/help/imagenes/icono_rakarrack_128x128.png.
We should have a contest!!!

**Comment by Rippert** [comment]
Hey Stazed, do you not like the guitar icon, or are you just interested in making it obvious that it is Rakarrack-Plus and not the old Rakarrack? I ask because I actually thought the guitar icon was one of the better ones in linux music apps.

**Comment by Stazed** [comment]
Yeah, I like the original also. Making it obvious that it is Rakarrack-Plus is the issue for me.

**Comment by Rippert** [comment]
OK, I'll give it some thought. 

> We should have a contest!!!

What do I win?

**Comment by Stazed** [comment]
I'll put the winners name on the README and in the help. You'll be famous!!!

**Comment by Stazed** [comment]
Congratulations to the winner... The competition was fierce!
In 1.1.0.
