### ISSUE TITLE
Remove Release from tags

### ISSUE THREAD

**Issue by fpesari** [Stazed/rakarrack-plus#18]
Hello,

I am making an openSUSE package for rakarrack-plus. Having "release" in release tag is a bit nonstandard, could you please use simple version numbers like `1.0.5`, so that the tarball is named `rakarrack-plus-1.0.5`? Thank you!

**Comment by Stazed** [comment]
I figured it would be hard to keep this one under the radar!!
Being unfamiliar with distribution packaging, I vaguely knew that there was a tarball generated and  never noticed it was named after the release tag....  Will use your suggestion in the future.
Leaving this open to remind me.
Thanks.

**Comment by Stazed** [comment]
Next major release out 1.1.0. Closing this now.
