### ISSUE TITLE
Can we merge projects?

### ISSUE THREAD

**Issue by ssj71** [Stazed/rakarrack-plus#2]
Hi Stazed. I didn't know that you were working on this project for a long time. I'm very glad you are. I'd like to merge our projects and work together. Do you see any obstacles for doing so? AFAICT I think I can just close out rkrlv2 and point people here since you have the plugins merged already IIUC. Does that seem appropriate? Lets talk about it. If you'd like to discuss on IRC or something let me know, or we can email, or discuss here, whatever you prefer.

**Comment by Stazed** [comment]
Hello @ssj71 

> I'd like to merge our projects and work together. Do you see any obstacles for doing so?

One of the reasons that I have not informed anyone about this project is that I have no DSP background. All the work is c++ programming only. The project could use the assistance of someone with DSP experience. The obstacle for me would be if you do not have the time, etc. and I would be left not being able to answer, fix DSP related issues. I have a few DSP questions of my own that I would like answered for the project as well. Would you be willing to handle the DSP side of things? If not, do you know someone qualified that would?

> I think I can just close out rkrlv2 and point people here since you have the plugins merged already

Yes the plugins are already merged. There are some noted differences, and the URIs have been changed.
There have been others interested in publishing the earlier version of this project as the official rakarrack. Unless someone is available to work on the DSP issues, I really do not feel comfortable in that capacity.

Appreciate any feedback...

**Comment by falkTX** [comment]
related to this, I would like to request that fixes made to the lv2 plugins are sent back to the rkrlv2 project please.
the scope of rkrlv2 is well defined - having the "old" rakarrack plugins in lv2 form. for this new fork, not so much..

Focusing on the lv2 plugins separately from the standalone is a good step to take IMO, since there are a lot of restrictions/rules for plugins that do not apply to standalones.

**Comment by Stazed** [comment]
@falkTX 

I believe you are misinterpreting ssj71's  request to merge. The title is a little misleading. IMO he no longer has the time to maintain rkrlv2 and wished to close his project with a note to his users pointing to this repository.

FYI this repository builds both LV2s and a version of rakarrack >> "rakarrack-plus". The LV2s were originally based on rkrlv2, but are now incompatible with them. The LV2 URIs have been changed for this reason.

As far as the scope of this project, to have a working stable version of standalone rakarrack, and also build the effects as LV2s merged in one project using the same source code. This has been completed. The  "restrictions/rules for plugins that do not apply to  standalones" have already been resolved.
