### ISSUE TITLE
make does not rebuild the UI if .fl files are modified

### ISSUE THREAD

**Issue by fpesari** [Stazed/rakarrack-plus#22]
I modified the .fl files both manually and in `fluid`, then I ran 

```
make clean
make
``` 

but the build program in `./src/rakarrack-plus` did not change its interface and looked just like it did before.

**Comment by Stazed** [comment]
The program does not compile .fl files. To update you need to either open each .fl file in FLUID and go to File/Write Code.
This will update the .cxx and .h related files in the same directory. Or, if doing wholesale changes with sed, you need to make the changes in all related files: .fl, .cxx, .h.

**Comment by fpesari** [comment]
I see fluid has a `-c` option to compile `.fl` files. Could it be implemented into the makefile, either as a `make ui` command or into regular `make`? I can implement it, no probs, would you be willing to merge it?

**Comment by Stazed** [comment]
No thanks, I prefer generating the .cxx files.
