### ISSUE TITLE
/nsm/client/gui_visible missing somewhere at startup

### ISSUE THREAD

**Issue by Houston4444** [Stazed/rakarrack-plus#29]
When r-plus is started under NSM with GUI visible, it forgets to send to NSM server /nsm/client/gui_visible.
Then the r-plus GUI is hidden for the NSM server GUI, and click on the GUI button changes nothing (it make NSM server send to rakarrack-plus /nsm/client/show_optional_gui, but the r-plus GUI is already shown in reality).

to reproduce:
* add rakkarack-plus to the current session
* show its GUI
* save and close the session
* reload this session

**Comment by Stazed** [comment]
There is a fix in the wip branch. I could not duplicate your behavior on my end, everything worked as it should without the fix. Could you confirm if this is working for you now. The terminal log for NSM shows that it is now receiving gui show on start for me.

**Comment by Houston4444** [comment]
Yes it works here ! Thanks
