### ISSUE TITLE
Does R+ have fix for this Harmonizer issue seen on ssj71/rkrlv2 ?

### ISSUE THREAD

**Issue by bdutta** [Stazed/rakarrack-plus#31]
https://github.com/ssj71/rkrlv2/issues/42

**Comment by Stazed** [comment]
I don't use Ardour and it would take me a while to figure out how to set this up. Perhaps you can get the originator of the issue to test with R+ LV2s. There have been some issues fixed in R+ related to the Harmonizer effects, that were not fixed in rkrlv2.
