### ISSUE TITLE
Default user directory

### ISSUE THREAD

**Issue by cbix** [Stazed/rakarrack-plus#37]
The user directory preference is by default set to `DATADIR` which is defined as `DATADIR="${CMAKE_INSTALL_PREFIX}/share/rakarrack-plus"`. This however is usually not writable by the user and @jujudusud reported this caused R+ to display an error on launch.

Ideally R+ should
- default this pref (see `src/Config_fltk.C`) to something like `~/.rakarrack-plus` or `~/.local/share/rakarrack-plus`
- create this directory automatically on first launch

**Comment by Stazed** [comment]
The user directory is not required to be set.
It is for advanced users who wish to create their own user banks,
custom effect presets and use custom user files for Convolotron, Echotron and Reverbtron.

The "error" message is really just a reminder and only shows when running in a terminal:
    No User Directory Set. Cannot load insert presets!

Perhaps a less threatening message would be better...

To eliminate the message you can go to Settings/Preferences/User : User Directory,
and use the Browse button to pick a location where you want to save things.
The location must be writable and the name is entirely up to the user.

For additional information about this and advanced usage, F1 help under Preferences.

**Comment by cbix** [comment]
It's actually an error message window saying _Cannot access User Directory at: /usr/share/rakarrack-plus Do you have permission? Is the User Directory a valid read/write folder?_

And it seems to prevent the application from launching. I know users can work around this by changing the setting, all I'm requesting is simply to have a default setting where this doesn't happen in the first place :)

**Comment by Stazed** [comment]
The only way for the error message that you indicate to occur is if the User directory is different from DATADIR. How is the program being installed? Perhaps it was previously installed, deleted and re-installed in a new location? Are you attempting to run without installing? Did someone change the User directory to the invalid location?

Try deleting the FLTK settings file in ~/.fltk/github.com.Stazed.rakarrack.plus/rakarrack-plus.prefs, and restart.

**Comment by Stazed** [comment]
Upon further investigation, the error message occurs when  opendir() fails for some reason. But the call to opendir() will not happen unless the USER directory is different from DATADIR. Not sure how this is happening. Is the program being installed on a network by someone other than the user?
Perhaps the user might have access to the program but opendir() fails because they do not have access to the network directory?
Something very strange is going on...

**Comment by cbix** [comment]
> the call to opendir() will not happen unless the USER directory is different from DATADIR

This probably explains @jujudusud error after installing the version we built for the [archlinux-proaudio](https://arch.osamc.de/#x86_64/rakarrack-plus) repo. There must have been a preferences file from a manual installation (which installs by default to `/usr/local`) and now that the binary package installs to `/usr` the DATADIR is different.

I'll close this issue again because I could not reproduce it from a fresh install and it will not affect users who didn't manually build & install rakarrack-plus themselves :)

**Comment by Stazed** [comment]
In the next release, the User directory will not be set by default to DATADIR and will be blank. This should prevent this type of problem from happening in the future on new installs. The setting of the User directory to DATADIR was a carryover from original Rakarrack that was not necessary.

**Comment by cbix** [comment]
> will not be set by default to DATADIR and will be blank

This will trigger the same error, or are you also changing the `opendir()` check so it doesn't happen by default?

In my opinion the best solution would be to actually create a `~./.rakarrack-plus` in the user's home directory so there is a writable user dir without any setup needed.

**Comment by Stazed** [comment]
> This will trigger the same error, or are you also changing the opendir() check so it doesn't happen by default?`

The new will check for both blank or DATADIR so it will not generate an error for new installs. It won't fix any previous problems though.

The reason for not setting the user directory for the user is that it will contain information that should be backed up by the user, so they should actively know where it is. In addition, the user directory can be copied to another computer with a different file structure, selected and the custom settings will work.
