### ISSUE TITLE
Could NOT find FLTK error

### ISSUE THREAD

**Issue by ScrawnyPetauro** [Stazed/rakarrack-plus#41]
Hi! I am trying to compile this on Fedora 37. I have installed both the `fltk` and `fltk-devel` packages, but I get this:

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FLTK (missing: FLTK_FLUID_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindFLTK.cmake:329 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:81 (find_package)
```

Do you have any idea how to solve this?

Thanks!

**Comment by Stazed** [comment]
I looks line fltk-fluid is not installed. Try:
> sudo dnf -y install fltk-fluid


Fluid is not required by R+ but may be needed by fltk-devel.  My fedora vm is 36 and I believe fltk-fluid was automatically installed with fltk-devel.  If fltk-fluid is already installed, then try asking someone with fedora distro forum and let me know if you find an answer, and I need to do something at this end.

**Comment by ScrawnyPetauro** [comment]
That solved it! Thanks a lot mate!

The only one thing I would point out to all those using Fedora 37 with Pipewire (which comes by default), is that that will have to install the `pipewire-jack-audio-connection-kit` and `pipewire-jack-audio-connection-kit-devel` packages instead of `jack-audio-connection-kit` and `pipewire-jack-audio-connection-kit-devel`
