### ISSUE TITLE
Documentation: add information about the aux jack input

### ISSUE THREAD

**Issue by ycollet** [Stazed/rakarrack-plus#49]
When starting rakarrack-plus, an "aux" jack input is displayed.
I really don't know want this input is for.
Can you add a little paragraph about this input in the doc ?

**Comment by Stazed** [comment]
The "aux" input is used for the Vocoder voice input. See Effects/Vocoder in the help. Also, it can be used as input for the Analog Control Interface where it is set for "aux" as default. Not sure where would be a good place to indicate its purpose other than in those places. Any ideas?

**Comment by ycollet** [comment]
Thanks for these info !

**Comment by ycollet** [comment]
Maybe adding a description part in general.html where all the jack ports are described ?

**Comment by Stazed** [comment]
Added to wip branch, in general.html with links.
